# Generated by Django 4.1.3 on 2022-12-04 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMI', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tavsif', models.CharField(max_length=50)),
                ('rasm', models.ImageField(upload_to='madia')),
                ('vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.homet')),
            ],
        ),
    ]
