# Generated by Django 4.1.3 on 2022-12-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_abut_abus'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMI', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='skillrasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='madia')),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tavsif', models.CharField(max_length=50)),
                ('vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.skill')),
            ],
        ),
    ]
