# Generated by Django 4.1.3 on 2022-12-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_skill_skillrasm_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio_rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMI', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='portfoliorasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='madia')),
                ('vaqt', models.DateTimeField(auto_now=True)),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.homet')),
            ],
        ),
    ]
