# Generated by Django 4.1.3 on 2022-12-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_portfolio_rasm_portfoliorasm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='portfoliorasm',
            name='nomi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.portfolio_rasm'),
        ),
    ]
