# Generated by Django 4.1.3 on 2022-12-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_message_alter_portfoliorasm_nomi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skillrasm',
        ),
        migrations.AddField(
            model_name='skills',
            name='rasm',
            field=models.ImageField(default=1, upload_to='madia'),
            preserve_default=False,
        ),
    ]
